### PR TITLE
Fixed flash notices getting displayed

### LINKED ISSUE #249: If you try and sign up when you are already signed in it goes straight to the show page no explanation

### PR DESCRIPTION
**Pull request by i-nomads**
Fixes #249 

I need someone to double-check that the flash is supposed to look like this. It was never shown apparently so we may have surprises.

### CODE REVIEW

**Comment by cdimitroulas** [comment]
is this simply to show the flash notification saying "you are already signed in" ?

**Comment by i-nomads** [comment]
Yes, but it may display all other ones that SHOULD have been there until now. As all flashes were disabled…

**Comment by cdimitroulas** [comment]
yeah you are right, I think it was disabled on purpose at some point as we decided the flashes didn't look that good. But maybe it's better for them to be there.
I will do some tests on this branch and take screenshots before merging

**Comment by cdimitroulas** [comment]
I think the alerts/notices look bad in certain places so it would be better to render them directly in the pages where they are needed rather than in the main application layout html. What do you think?

A few places where it is necessary -> edit user profile form, main user landing page, bank user dashboard
image

image

image

**Pull request merged**
